var says = [
   "<style>.splash-text{ color:cyan;}</style>Credit to 3kh0",
   "<style>.splash-text{ color:cyan;}</style>3kh0 rocks",
   "<style>.splash-text{ color:cyan;}</style>Check out <a href='https://3kh0.github.io' target='_blank'>3kh0.github.io</a> also",
   "murhahaha",
   "<style>.splash-text{ color:red;}</style>give me your vbux",
   "Sorry for the ads",
   "I need my moolah",
   "erm what the sigma",
   "<style>.splash-text{ color:cyan;}</style>3kh0 reference",
   "Giggity",
   "Geometry tryhard V3!!",
   "Check out ultraviolet up top",
   "<u>All Content belongs to its respectful owners.</u>",
   "Does anyone even scroll all the way down?",
   "<style>.splash-text{ color:cyan;}</style>3kh0 is awesome",
   "Redbull gives you wiings",
   "If you skid please submit the link in Alternate links!",
   "Tell me to add games up top",
   "<style>.splash-text{ color:#20C20E;}</style>Ж呖N%@ωψ흥",
   "loads of games",
   "optimized by Opera AI",
   "y'all don't know me",
   "https://discord.gg/auxXTY8x8P",
   "https://discord.gg/auxXTY8x8P also",
   "https://discord.gg/auxXTY8x8P again?",
   "💀💀💀",
   "why",
   "how",
   "when",
   "what", 
   "uh", 
   "y'all need to look better before requesting a game I already added...", 
   "Primus sucks", 
   "Miscellaneous Debris", 
   "the person who made this websites pretty cool i think", 
   "when do I get to go home?", 
   "many hours wasted", 
   "shut up ryan",
   "<style>.splash-text{ color:cyan;}</style>3kh0",
   "why do i do this?",
  "🗿",
  "🗿🗿",
  "🗿🗿🗿",
  "🍷🗿",
  "️‍🔥",
  "1 in 50 &middot; screenshot",
  "moyai",
  "yesn't",
  "mayhaps",
  "nope",
 ];

function splashText() {
  document.querySelector(".splash-text").innerHTML =
    says[Math.floor(Math.random() * says.length)];
}
